AUCTION_CREATED = "auction_created"
AUCTION_UPDATED = "auction_updated"
AUCTION_STARTED = "auction_started"
AUCTION_CANCELLED = "auction_cancelled"
AUCTION_ENDED = "auction_ended"
BID_CREATED = "new_bid"
BUY_NOW_COMPLETED = "buy_now"
