services:

  nginx:
    image: nginx:0.0.1
    pull_policy: never
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - frontend
    ports:
      - "443:443"
    networks:
      - bidlive_network
    restart: always
    env_file:
      - ./.env

  grafana:
    image: grafana:0.0.1
    pull_policy: never
    build:
      context: ./requirements/grafana
      dockerfile: Dockerfile
    container_name: grafana
    depends_on:
      prometheus:
        condition: service_started
    networks:
      - bidlive_network
    restart: always
    secrets:
      - grafana_credenciais
    env_file:
      - ./.env.grafana

  prometheus:
    image: prometheus:0.0.1
    pull_policy: never
    build:
      context: ./requirements/prometheus
      dockerfile: Dockerfile
    container_name: prometheus
    depends_on:
      - backend
      - celery_worker
      - celery_beat
    networks:
      - bidlive_network
    restart: always
    volumes:
      - prometheus_data:/prometheus

  frontend:
    image: frontend:0.0.1
    pull_policy: never
    build:
      context: ./requirements/frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
      - celery_worker
      - celery_beat
    networks:
      - bidlive_network
    restart: always
    env_file:
      - ./.env.frontend

  celery_beat:
    image: backend:0.0.1
    pull_policy: never
    build:
      context: ./requirements/backend
      dockerfile: Dockerfile
    container_name: celery_beat
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_started
      backend:
        condition: service_started
    networks:
      - bidlive_network
    restart: always
    env_file:
      - ./.env.backend
      - ./.env.db
      - ./.env.redis
      - ./.env.livekit
    secrets:
      - db_credenciais
      - redis_credenciais
      - livekit_credenciais
      - backend_credenciais
      - 42_credenciais
      - google_credenciais
    environment:
      SERVICE_ROLE: celery-beat

  celery_worker:
    image: backend:0.0.1
    pull_policy: never
    build:
      context: ./requirements/backend
      dockerfile: Dockerfile
    container_name: celery_worker
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_started
      backend:
        condition: service_started
    networks:
      - bidlive_network
    restart: always
    env_file:
      - ./.env.backend
      - ./.env.db
      - ./.env.redis
      - ./.env.livekit
    secrets:
      - db_credenciais
      - redis_credenciais
      - livekit_credenciais
      - backend_credenciais
      - 42_credenciais
      - google_credenciais
    environment:
      SERVICE_ROLE: celery-worker

  backend:
    image: backend:0.0.1
    pull_policy: never
    build:
      context: ./requirements/backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_started
      livekit:
        condition: service_started
    networks:
      - bidlive_network
    restart: always
    env_file:
      - ./.env.backend
      - ./.env.db
      - ./.env.redis
      - ./.env.livekit
    secrets:
      - db_credenciais
      - redis_credenciais
      - livekit_credenciais
      - backend_credenciais
      - 42_credenciais
      - google_credenciais
    environment:
      SERVICE_ROLE: django

  livekit:
    image: livekit:0.0.1
    pull_policy: never
    build:
      context: ./requirements/livekit
      dockerfile: Dockerfile
    container_name: livekit
    depends_on:
      redis:
        condition: service_started
    networks:
      - bidlive_network
    restart: always
    env_file:
      - ./.env.livekit
      - ./.env.redis
    secrets:
      - redis_credenciais
      - livekit_credenciais

  adminer:
    image: adminer:0.0.1
    pull_policy: never
    build:
      context: ./requirements/adminer
      dockerfile: Dockerfile
    container_name: adminer
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - bidlive_network
    restart: always

  postgresql:
    image: postgresql:0.0.1
    pull_policy: never
    build:
      context: ./requirements/postgresql
      dockerfile: Dockerfile
    container_name: postgresql
    networks:
      - bidlive_network
    restart: always
    env_file:
      - ./.env.db
    secrets:
      - db_credenciais
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:0.0.1
    pull_policy: never
    build:
      context: ./requirements/redis
      dockerfile: Dockerfile
    container_name: redis
    networks:
      - bidlive_network
    restart: always
    env_file:
      - ./.env.redis
    secrets:
      - redis_credenciais
    volumes:
      - redis_data:/data

  portainer:
    image: portainer:0.0.1
    pull_policy: never
    build:
      context: ./requirements/portainer
      dockerfile: Dockerfile
    container_name: portainer
    networks:
      - bidlive_network
    restart: always
    secrets:
      - portainer_credenciais
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

secrets:
  db_credenciais:
    file: ../secrets/db_credenciais.txt
  redis_credenciais:
    file: ../secrets/redis_credenciais.txt
  livekit_credenciais:
    file: ../secrets/livekit_credenciais.txt
  backend_credenciais:
    file: ../secrets/backend_credenciais.txt
  42_credenciais:
    file: ../secrets/42_credenciais.txt
  google_credenciais:
    file: ../secrets/google_credenciais.txt
  grafana_credenciais:
    file: ../secrets/grafana_credenciais.txt
  portainer_credenciais:
    file: ../secrets/portainer_credenciais.txt

networks:
  bidlive_network:
    driver: bridge
    name: bidlive_network

volumes:
  redis_data:
    driver: local

  postgresql_data:
    driver: local

  prometheus_data:
    driver: local

  portainer_data:
    driver: local
