services:

  nginx:
    image: nginx:0.0.1
    pull_policy: never
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - frontend
    ports:
      - "443:443"
    networks:
      - bidlive_network
    restart: always
    env_file:
      - ./.env

  adminer:
    image: adminer:0.0.1
    pull_policy: never
    build:
      context: ./requirements/adminer
      dockerfile: Dockerfile
    container_name: adminer
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - bidlive_network
    restart: always
    env_file:
      - ./.env

  frontend:
    image: frontend:0.0.1
    pull_policy: never
    build:
      context: ./requirements/frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    networks:
      - bidlive_network
    restart: always
    env_file:
      - ./.env

  backend:
    image: backend:0.0.1
    pull_policy: never
    build:
      context: ./requirements/backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_started
      livekit:
        condition: service_started
    networks:
      - bidlive_network
    restart: always
    env_file:
      - ./.env
    secrets:
      - redis_password
    environment:
      SERVICE_ROLE: django

  celery_worker:
    image: backend:0.0.1
    pull_policy: never
    build:
      context: ./requirements/backend
      dockerfile: Dockerfile
    container_name: celery_worker
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_started
      backend:
        condition: service_started
    networks:
      - bidlive_network
    restart: always
    env_file:
      - ./.env
    secrets:
      - redis_password
    environment:
      SERVICE_ROLE: celery-worker

  celery_beat:
    image: backend:0.0.1
    pull_policy: never
    build:
      context: ./requirements/backend
      dockerfile: Dockerfile
    container_name: celery_beat
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_started
      backend:
        condition: service_started
    networks:
      - bidlive_network
    restart: always
    env_file:
      - ./.env
    secrets:
      - redis_password
    environment:
      SERVICE_ROLE: celery-beat

  livekit:
    image: livekit:0.0.1
    pull_policy: never
    build:
      context: ./requirements/livekit
      dockerfile: Dockerfile
    container_name: livekit
    depends_on:
      redis:
        condition: service_started
    networks:
      - bidlive_network
    restart: always
    env_file:
      - ./.env

  prometheus:
    image: prometheus:0.0.1
    pull_policy: never
    build:
      context: ./requirements/prometheus
      dockerfile: Dockerfile
    container_name: prometheus
    depends_on:
      backend:
        condition: service_started
    networks:
      - bidlive_network
    restart: always
    env_file:
      - ./.env
    volumes:
      - prometheus_data:/prometheus

  grafana:
    image: grafana:0.0.1
    pull_policy: never
    build:
      context: ./requirements/grafana
      dockerfile: Dockerfile
    container_name: grafana
    depends_on:
      prometheus:
        condition: service_started
    networks:
      - bidlive_network
    restart: always
    env_file:
      - ./.env
    secrets:
      - grafana_password
    environment:
      GF_SECURITY_ADMIN_PASSWORD_FILE: /run/secrets/grafana_password

  postgresql:
    image: postgresql:0.0.1
    pull_policy: never
    build:
      context: ./requirements/postgresql
      dockerfile: Dockerfile
    container_name: postgresql
    networks:
      - bidlive_network
    restart: always
    secrets:
      - db_credenciais
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:0.0.1
    pull_policy: never
    build:
      context: ./requirements/redis
      dockerfile: Dockerfile
    container_name: redis
    networks:
      - bidlive_network
    restart: always
    secrets:
      - redis_credenciais
    volumes:
      - redis_data:/data

  portainer:
    image: portainer/portainer-ce:2.39.3-alpine
    container_name: portainer
    command: --base-url=/portainer
    networks:
      - bidlive_network
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

secrets:
  db_credenciais:
    file: ../secrets/db_credenciais.txt
  grafana_credenciais:
    file: ../secrets/grafana_credenciais.txt
  redis_credenciais:
    file: ../secrets/redis_credenciais.txt

networks:
  bidlive_network:
    driver: bridge
    name: bidlive_network

volumes:
  redis_data:
    driver: local

  postgresql_data:
    driver: local

  prometheus_data:
    driver: local

  portainer_data:
    driver: local
