# Generated by Django 5.2.14 on 2026-05-19 02:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domain", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Project",
            new_name="Domain",
        ),
        migrations.AlterModelTable(
            name="domain",
            table="domain_project",
        ),
    ]
