# Generated by Django 5.2.14 on 2026-05-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('NEW_BID', 'New Bid'), ('OUTBID', 'Outbid'), ('MESSAGE', 'Message'), ('FRIEND_REQUEST', 'Friend Request'), ('STREAM_STARTED', 'Stream Started'), ('STREAM_ENDED', 'Stream Ended'), ('STREAM_CANCELLED', 'Stream Cancelled'), ('FEATURED_STREAM', 'Featured Stream'), ('AUCTION_ENDED', 'Auction Ended')], max_length=30),
        ),
    ]
