# Generated by Django 5.2.14 on 2026-05-21 10:00

from django.db import migrations
from django.utils.text import slugify


DEFAULT_CATEGORIES = [
    "Electronics",
    "Fashion",
    "Vehicles",
    "Gaming",
    "Art",
    "Collectibles",
    "Real Estate",
    "Other",
]


def seed_categories(apps, schema_editor):
    AuctionCategory = apps.get_model("auctions", "AuctionCategory")
    for name in DEFAULT_CATEGORIES:
        AuctionCategory.objects.get_or_create(
            name=name,
            defaults={"slug": slugify(name), "is_active": True, "sort_order": 0},
        )


def unseed_categories(apps, schema_editor):
    AuctionCategory = apps.get_model("auctions", "AuctionCategory")
    AuctionCategory.objects.filter(name__in=DEFAULT_CATEGORIES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_auction_module"),
    ]

    operations = [
        migrations.RunPython(seed_categories, unseed_categories),
    ]
