# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_remove_auctionitem_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="ip_address",
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name="bid",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterModelOptions(
            name="bid",
            options={
                "db_table": "bids",
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Bid",
                "verbose_name_plural": "Bids",
            },
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(
                fields=["auction", "-amount", "created_at"],
                name="idx_bids_auction_amount",
            ),
        ),
    ]
