# Generated by Codex on 2026-05-29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_bid_realtime_enhancements"),
        ("storage", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="livestream",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="livestream",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("READY", "Ready"),
                    ("LIVE", "Live"),
                    ("ENDED", "Ended"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="livestream",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public"),
                    ("UNLISTED", "Unlisted"),
                    ("PRIVATE", "Private"),
                ],
                default="PUBLIC",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="livestream",
            name="stream_key_hash",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="livestream",
            name="thumbnail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stream_thumbnails",
                to="storage.file",
            ),
        ),
        migrations.AddField(
            model_name="livestream",
            name="viewer_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="livestream",
            name="stream_meta",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="streamviewer",
            name="last_seen_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="livestream",
            index=models.Index(fields=["auction"], name="idx_streams_auction"),
        ),
        migrations.AddIndex(
            model_name="livestream",
            index=models.Index(fields=["status"], name="idx_streams_status"),
        ),
        migrations.AddIndex(
            model_name="livestream",
            index=models.Index(fields=["is_live"], name="idx_streams_live"),
        ),
    ]
