# Generated by Django 5.2.14 on 2026-06-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_livestream_enhancements"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
