# Generated by Django 5.2.14 on 2026-07-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_remove_auctionimage_uniq_auction_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SCHEDULED", "Scheduled"),
                    ("ACTIVE", "Active"),
                    ("LIVE", "Live"),
                    ("ENDED", "Ended"),
                    ("CANCELLED", "Cancelled"),
                    ("SOLD", "Sold"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
