# Generated by Django 5.2.14 on 2026-05-14 20:20

from django.db import migrations, models


def seed_roles_permissions(apps, schema_editor):
    Role = apps.get_model("users", "Role")
    Permission = apps.get_model("users", "Permission")
    RolePermission = apps.get_model("users", "RolePermission")

    permissions_by_role = {
        "USER": [
            "auction.read",
            "auction.bid",
            "project.read",
        ],
        "ADMIN": [
            "admin.manage",
            "auction.read",
            "auction.bid",
            "project.read",
            "project.write",
        ],
    }

    for role_name, permission_names in permissions_by_role.items():
        role, _ = Role.objects.get_or_create(name=role_name, defaults={"description": f"{role_name} role"})
        for permission_name in permission_names:
            permission, _ = Permission.objects.get_or_create(
                name=permission_name,
                defaults={"description": permission_name},
            )
            RolePermission.objects.get_or_create(role=role, permission=permission)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="failed_login_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login_ip",
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name="user",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(seed_roles_permissions, migrations.RunPython.noop),
    ]
