# Generated by Django 5.2.14 on 2026-05-14 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auctions", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_auctions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auctionitem",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auction_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auctions",
                to="auctions.auctionitem",
            ),
        ),
        migrations.AddField(
            model_name="auctionwatcher",
            name="auction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchers",
                to="auctions.auction",
            ),
        ),
        migrations.AddField(
            model_name="auctionwatcher",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auction_watches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="auction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="auctions.auction",
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="bidder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="livestream",
            name="auction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="streams",
                to="auctions.auction",
            ),
        ),
        migrations.AddField(
            model_name="livestream",
            name="streamer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="streams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="streamviewer",
            name="stream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="viewers",
                to="auctions.livestream",
            ),
        ),
        migrations.AddField(
            model_name="streamviewer",
            name="viewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stream_views",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="auctionitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_price__gte", models.F("starting_price"))),
                name="check_item_current_price_gte_starting",
            ),
        ),
        migrations.AddIndex(
            model_name="auction",
            index=models.Index(fields=["status"], name="idx_auctions_status"),
        ),
        migrations.AddIndex(
            model_name="auction",
            index=models.Index(fields=["end_time"], name="idx_auctions_end_time"),
        ),
        migrations.AddConstraint(
            model_name="auction",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))),
                name="check_auction_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="auctionwatcher",
            constraint=models.UniqueConstraint(
                fields=("auction", "user"), name="uniq_auction_watcher"
            ),
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(fields=["auction"], name="idx_bids_auction"),
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(fields=["bidder"], name="idx_bids_bidder"),
        ),
        migrations.AddConstraint(
            model_name="bid",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="check_bid_amount_gt_zero"
            ),
        ),
        migrations.AddConstraint(
            model_name="streamviewer",
            constraint=models.UniqueConstraint(
                fields=("stream", "viewer"), name="uniq_stream_viewer"
            ),
        ),
    ]
