# Generated by Django 5.2.14 on 2026-05-21 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_initial"),
        ("storage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="auctionitem",
            old_name="category",
            new_name="category_label",
        ),
        migrations.CreateModel(
            name="AuctionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="auctions.auctioncategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auction Category",
                "verbose_name_plural": "Auction Categories",
                "db_table": "auction_categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="auctionitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="auctions.auctioncategory",
            ),
        ),
        migrations.AddField(
            model_name="auctionitem",
            name="minimum_increment",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name="auctionitem",
            name="reserve_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name="auction",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SCHEDULED", "Scheduled"),
                    ("LIVE", "Live"),
                    ("ENDED", "Ended"),
                    ("CANCELLED", "Cancelled"),
                    ("SOLD", "Sold"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="buy_now_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auction",
            name="buy_now_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buy_now_auctions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="cancel_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="auction",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auction",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_auctions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auction",
            name="reserve_met",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="auction",
            name="rules",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auction",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auction",
            name="winning_bid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="winning_auctions",
                to="auctions.bid",
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="is_buy_now",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="AuctionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auction_images",
                        to="storage.file",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="auctions.auctionitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auction Image",
                "verbose_name_plural": "Auction Images",
                "db_table": "auction_images",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuctionAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(max_length=100)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auction_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="auctions.auction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auction Audit Log",
                "verbose_name_plural": "Auction Audit Logs",
                "db_table": "auction_audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="auction",
            index=models.Index(fields=["start_time"], name="idx_auctions_start_time"),
        ),
        migrations.AddIndex(
            model_name="auctioncategory",
            index=models.Index(fields=["slug"], name="idx_auction_category_slug"),
        ),
        migrations.AddIndex(
            model_name="auctionimage",
            index=models.Index(fields=["item"], name="idx_auction_images_item"),
        ),
        migrations.AddIndex(
            model_name="auctionauditlog",
            index=models.Index(fields=["action"], name="idx_auction_audit_action"),
        ),
        migrations.AddConstraint(
            model_name="auctionitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("starting_price__gte", 0)),
                name="check_item_starting_price_gte_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="auctionitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("minimum_increment__gt", 0)),
                name="check_item_min_increment_gt_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="auctionitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reserve_price__isnull", True)
                )
                | models.Q(("reserve_price__gte", models.F("starting_price"))),
                name="check_item_reserve_price_gte_starting",
            ),
        ),
        migrations.AddConstraint(
            model_name="auctionitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("buy_now_price__isnull", True))
                | models.Q(("buy_now_price__gte", models.F("starting_price"))),
                name="check_item_buy_now_price_gte_starting",
            ),
        ),
        migrations.AddConstraint(
            model_name="auctionimage",
            constraint=models.UniqueConstraint(fields=("item", "file"), name="uniq_auction_image"),
        ),
    ]
