# Generated by Django 5.2.14 on 2026-05-21 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_seed_categories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auctionitem",
            name="image_url",
        ),
        migrations.AlterField(
            model_name="auctionitem",
            name="condition_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NEW", "New"),
                    ("USED", "Used"),
                    ("REFURBISHED", "Refurbished"),
                    ("DAMAGED", "Damaged"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="bid",
            index=models.Index(fields=["auction", "created_at"], name="idx_bids_auction_time"),
        ),
    ]
