# Generated by Django 5.2.14 on 2026-06-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auction_is_featured'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='auctionimage',
            name='uniq_auction_image',
        ),
        migrations.RemoveField(
            model_name='auctionimage',
            name='file',
        ),
        migrations.AddField(
            model_name='auctionimage',
            name='image_url',
            field=models.URLField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='auctionimage',
            constraint=models.UniqueConstraint(fields=('item', 'image_url'), name='uniq_auction_image'),
        ),
    ]
