bind 0.0.0.0

port REDIS_PORT_PLACEHOLDER

user default off
user REDIS_USER_PLACEHOLDER on >REDIS_PASSWORD_PLACEHOLDER ~* &* +@all

protected-mode no

dir /data

loglevel notice

rename-command FLUSHALL ""