{
 "title": "LiveKit on Fly.io Metrics",
 "description": "Metrics for LiveKit servers running on Fly.io, grouped by Region. Could likely be easily adapter for other environments.",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "region",
    "query": {
     "query": "label_values(livekit_room_total,region)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Data Transfer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(fly_instance_net_sent_bytes{device=\"eth0\",region=~\"^$region$\"}[$__rate_interval])) by (region)",
     "legendFormat": "sent: {{region}}"
    },
    {
     "expr": "sum(rate(fly_instance_net_recv_bytes{device=\"eth0\",region=~\"^$region$\"}[$__rate_interval])) by (region)",
     "legendFormat": "recv: {{region}}"
    }
   ]
  },
  {
   "title": "Packet Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(livekit_packet_bytes{direction=\"outgoing\",region=~\"^$region$\"}[$__rate_interval])) by (region)",
     "legendFormat": "sent: {{region}}"
    },
    {
     "expr": "sum(rate(livekit_packet_bytes{direction=\"incoming\",region=~\"^$region$\"}[$__rate_interval])) by (region)",
     "legendFormat": "recv: {{region}}"
    }
   ]
  },
  {
   "title": "Rooms",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(livekit_room_total{region=~\"$region\"}) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Participants",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(livekit_participant_total{region=~\"$region\"}) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Published Audio Tracks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(livekit_track_published_total{kind=\"AUDIO\",region=~\"$region\"}) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Published Video Tracks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(livekit_track_published_total{kind=\"VIDEO\",region=~\"$region\"}) by (region)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Service Operation Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(livekit_node_service_operation{status!=\"success\", region=~\"$region\"}[$__rate_interval])) by (region, type, status) * $__rate_interval",
     "legendFormat": "({{status}}) {{region}}: {{type}}"
    }
   ]
  },
  {
   "title": "Participants Joined",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(livekit_node_service_operation{status=\"success\", type=\"participant_join\", region=~\"$region\"}[$__rate_interval])) by (region) * $__rate_interval",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Load Average: $region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "repeat": "region",
   "targets": [
    {
     "expr": "max(max_over_time(fly_instance_load_average{minutes=\"1\",region=\"$region\"}[$__rate_interval]))",
     "legendFormat": "1m"
    },
    {
     "expr": "max(max_over_time(fly_instance_load_average{minutes=\"5\",region=\"$region\"}[$__rate_interval]))",
     "legendFormat": "5m"
    },
    {
     "expr": "max(max_over_time(fly_instance_load_average{minutes=\"15\",region=\"$region\"}[$__rate_interval]))",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Memory Usage: $region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "repeat": "region",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(fly_instance_memory_mem_total{region=\"$region\"})",
     "legendFormat": "total"
    },
    {
     "expr": "avg(fly_instance_memory_mem_total{region=\"$region\"}) - avg(fly_instance_memory_mem_free{region=\"$region\"})",
     "legendFormat": "used"
    }
   ]
  }
 ]
}