{
 "title": "a Nginx Connections Overview",
 "description": "Shows stats from nginx/nginx-prometheus-exporter (official). Adapted from gnetId 9512.",
 "tags": [
  "nginx",
  "http"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(nginx_up, namespace)"
   },
   {
    "name": "app",
    "query": "label_values(nginx_up{namespace=~\"$namespace\"}, app)"
   },
   {
    "name": "instance",
    "query": "label_values(nginx_up{namespace=~\"$namespace\",  app=~\"$app\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_up{namespace=~\"$namespace\", app=~\"$app\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Processed Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 22, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_connections_handled{instance=~\"$instance\", app=~\"$app\", namespace=~\"$namespace\"}[5m])",
     "legendFormat": "[{{app}}] Handled connections"
    },
    {
     "expr": "irate(nginx_connections_accepted{instance=~\"$instance\", app=~\"$app\", namespace=~\"$namespace\"}[5m])",
     "legendFormat": "[{{app}}] Accepted connections"
    },
    {
     "expr": "irate(nginx_http_requests_total{instance=~\"$instance\", app=~\"$app\", namespace=~\"$namespace\"}[5m])",
     "legendFormat": "[{{app}}] HTTP requests"
    }
   ]
  },
  {
   "title": "Exporter Uptime",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 7 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"nginx_exporter\", app=~\"$app\", instance=~\"$instance\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 22, "x": 2, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_active{app=~\"$app\", instance=~\"$instance\", namespace=~\"$namespace\"}",
     "legendFormat": "[{{app}}] Active connections"
    },
    {
     "expr": "nginx_connections_reading{app=~\"$app\", instance=~\"$instance\", namespace=~\"$namespace\"}",
     "legendFormat": "[{{app}}] Reading (request header)"
    },
    {
     "expr": "nginx_connections_writing{app=~\"$app\", instance=~\"$instance\", namespace=~\"$namespace\"}",
     "legendFormat": "[{{app}}] Writing (response)"
    },
    {
     "expr": "nginx_connections_waiting{app=~\"$app\", instance=~\"$instance\", namespace=~\"$namespace\"}",
     "legendFormat": "[{{app}}] Waiting (idle)"
    }
   ]
  }
 ]
}