#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SECRETS_DIR="${SCRIPT_DIR}/../../secrets"

# Ensure secrets directory exists
mkdir -p "${SECRETS_DIR}"

# Canonicalize secrets directory path to avoid issues with '..' inside Docker volume mounts
SECRETS_DIR="$(cd "${SECRETS_DIR}" && pwd)"

echo "🔑 BidLive Root CA Generator"
echo "📁 Secrets directory: ${SECRETS_DIR}"

# Check if CA already exists
if [ -f "${SECRETS_DIR}/ca.pem" ] && [ -f "${SECRETS_DIR}/ca-key.pem" ]; then
    echo "✅ Root CA already exists in ${SECRETS_DIR}"
    echo "   - ca.pem (certificate)"
    echo "   - ca-key.pem (private key)"
    echo ""
    echo "To regenerate, delete these files first."
    exit 0
fi

# Verify ca-csr.json and ca-config.json exist
if [ ! -f "${SECRETS_DIR}/ca-csr.json" ]; then
    echo "❌ Missing ${SECRETS_DIR}/ca-csr.json"
    exit 1
fi

if [ ! -f "${SECRETS_DIR}/ca-config.json" ]; then
    echo "❌ Missing ${SECRETS_DIR}/ca-config.json"
    exit 1
fi

echo "⚙️  Generating Root CA using cfssl (via Docker)..."

# Generate Root CA
docker run --rm -i \
    -v "${SECRETS_DIR}:${SECRETS_DIR}" \
    -w "${SECRETS_DIR}" \
    cfssl/cfssl gencert -initca "${SECRETS_DIR}/ca-csr.json" \
    | docker run --rm -i \
        --entrypoint cfssljson \
        -v "${SECRETS_DIR}:${SECRETS_DIR}" \
        -w "${SECRETS_DIR}" \
        cfssl/cfssl -bare "${SECRETS_DIR}/ca"

# Clean up the CSR file generated by cfssl
rm -f "${SECRETS_DIR}/ca.csr"

# Set proper permissions
chmod 644 "${SECRETS_DIR}/ca.pem"
chmod 600 "${SECRETS_DIR}/ca-key.pem"

echo ""
echo "✅ Root CA generated successfully!"
echo "   - ${SECRETS_DIR}/ca.pem (certificate)"
echo "   - ${SECRETS_DIR}/ca-key.pem (private key)"
echo ""
echo "⚠️  Keep ca-key.pem secure! It is the root of trust for all containers."
