# Generated by Django 5.2.14 on 2026-05-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="session",
            name="refresh_jti",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="session",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
