# Generated by Django 5.2.14 on 2026-05-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("USER", "User"),
                            ("MESSAGE", "Message"),
                            ("PRIVATE_MESSAGE", "Private Message"),
                            ("AUCTION", "Auction"),
                            ("AUCTION_ITEM", "Auction Item"),
                            ("BID", "Bid"),
                            ("STREAM", "Stream"),
                            ("FILE", "File"),
                        ],
                        max_length=30,
                    ),
                ),
                ("target_id", models.BigIntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("SPAM", "Spam"),
                            ("HARASSMENT", "Harassment"),
                            ("SCAM", "Scam"),
                            ("HATE_SPEECH", "Hate Speech"),
                            ("FRAUD", "Fraud"),
                            ("INAPPROPRIATE_CONTENT", "Inappropriate Content"),
                            ("COPYRIGHT", "Copyright"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("RESOLVED", "Resolved"),
                            ("REJECTED", "Rejected"),
                            ("IGNORED", "Ignored"),
                        ],
                        default="OPEN",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "db_table": "reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("COMMENT", "Comment"),
                            ("CHANGE_STATUS", "Change Status"),
                            ("WARN_USER", "Warn User"),
                            ("BAN_USER", "Ban User"),
                            ("DELETE_CONTENT", "Delete Content"),
                            ("ESCALATE", "Escalate"),
                        ],
                        max_length=30,
                    ),
                ),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Report Action",
                "verbose_name_plural": "Report Actions",
                "db_table": "report_actions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Report Evidence",
                "verbose_name_plural": "Report Evidence",
                "db_table": "report_evidence",
                "ordering": ["-created_at"],
            },
        ),
    ]
