# Generated by Django 5.2.14 on 2026-05-14 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chat", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="privateconversation",
            name="user_one",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="private_conversations_one",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="privateconversation",
            name="user_two",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="private_conversations_two",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="privatemessage",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.privateconversation",
            ),
        ),
        migrations.AddField(
            model_name="privatemessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["room"], name="idx_messages_room"),
        ),
        migrations.AddConstraint(
            model_name="privateconversation",
            constraint=models.UniqueConstraint(
                fields=("user_one", "user_two"), name="uniq_private_conversation"
            ),
        ),
        migrations.AddConstraint(
            model_name="privateconversation",
            constraint=models.CheckConstraint(
                condition=models.Q(("user_one", models.F("user_two")), _negated=True),
                name="check_private_users",
            ),
        ),
        migrations.AddIndex(
            model_name="privatemessage",
            index=models.Index(fields=["conversation"], name="idx_private_messages_conv"),
        ),
    ]
