apiVersion: 1

datasources:
  - name: Prometheus
    uid: Prometheus
    type: prometheus
    access: proxy
    url: https://prometheus:9090
    isDefault: true
    jsonData:
      tlsSkipVerify: true
    editable: true

  - name: Elasticsearch
    uid: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    isDefault: false
    jsonData:
      index: "bidlive-logs-*"
      timeField: "@timestamp"
      esVersion: "8.17.0"
      logMessageField: "message"
      logLevelField: "log_level"
    editable: true
